/**
 * 世界国家/地区数据
 * 包含 ISO 3166-1 alpha-3 代码、中英文名称、国旗 emoji、所属大洲
 * key 使用 ISO_A3 代码（与 GeoJSON 数据匹配）
 */
const COUNTRIES_DATA = {
    // ============ 亚洲 Asia ============
    "CHN": { zh: "中国", en: "China", flag: "🇨🇳", continent: "亚洲" },
    "JPN": { zh: "日本", en: "Japan", flag: "🇯🇵", continent: "亚洲" },
    "KOR": { zh: "韩国", en: "South Korea", flag: "🇰🇷", continent: "亚洲" },
    "PRK": { zh: "朝鲜", en: "North Korea", flag: "🇰🇵", continent: "亚洲" },
    "MNG": { zh: "蒙古", en: "Mongolia", flag: "🇲🇳", continent: "亚洲" },
    "TWN": { zh: "中国台湾", en: "Taiwan", flag: "🇹🇼", continent: "亚洲" },
    "HKG": { zh: "中国香港", en: "Hong Kong", flag: "🇭🇰", continent: "亚洲" },
    "MAC": { zh: "中国澳门", en: "Macao", flag: "🇲🇴", continent: "亚洲" },
    "VNM": { zh: "越南", en: "Vietnam", flag: "🇻🇳", continent: "亚洲" },
    "THA": { zh: "泰国", en: "Thailand", flag: "🇹🇭", continent: "亚洲" },
    "LAO": { zh: "老挝", en: "Laos", flag: "🇱🇦", continent: "亚洲" },
    "KHM": { zh: "柬埔寨", en: "Cambodia", flag: "🇰🇭", continent: "亚洲" },
    "MMR": { zh: "缅甸", en: "Myanmar", flag: "🇲🇲", continent: "亚洲" },
    "MYS": { zh: "马来西亚", en: "Malaysia", flag: "🇲🇾", continent: "亚洲" },
    "SGP": { zh: "新加坡", en: "Singapore", flag: "🇸🇬", continent: "亚洲" },
    "IDN": { zh: "印度尼西亚", en: "Indonesia", flag: "🇮🇩", continent: "亚洲" },
    "PHL": { zh: "菲律宾", en: "Philippines", flag: "🇵🇭", continent: "亚洲" },
    "BRN": { zh: "文莱", en: "Brunei", flag: "🇧🇳", continent: "亚洲" },
    "TLS": { zh: "东帝汶", en: "Timor-Leste", flag: "🇹🇱", continent: "亚洲" },
    "IND": { zh: "印度", en: "India", flag: "🇮🇳", continent: "亚洲" },
    "PAK": { zh: "巴基斯坦", en: "Pakistan", flag: "🇵🇰", continent: "亚洲" },
    "BGD": { zh: "孟加拉国", en: "Bangladesh", flag: "🇧🇩", continent: "亚洲" },
    "LKA": { zh: "斯里兰卡", en: "Sri Lanka", flag: "🇱🇰", continent: "亚洲" },
    "NPL": { zh: "尼泊尔", en: "Nepal", flag: "🇳🇵", continent: "亚洲" },
    "BTN": { zh: "不丹", en: "Bhutan", flag: "🇧🇹", continent: "亚洲" },
    "MDV": { zh: "马尔代夫", en: "Maldives", flag: "🇲🇻", continent: "亚洲" },
    "AFG": { zh: "阿富汗", en: "Afghanistan", flag: "🇦🇫", continent: "亚洲" },
    "IRN": { zh: "伊朗", en: "Iran", flag: "🇮🇷", continent: "亚洲" },
    "IRQ": { zh: "伊拉克", en: "Iraq", flag: "🇮🇶", continent: "亚洲" },
    "SYR": { zh: "叙利亚", en: "Syria", flag: "🇸🇾", continent: "亚洲" },
    "LBN": { zh: "黎巴嫩", en: "Lebanon", flag: "🇱🇧", continent: "亚洲" },
    "JOR": { zh: "约旦", en: "Jordan", flag: "🇯🇴", continent: "亚洲" },
    "ISR": { zh: "以色列", en: "Israel", flag: "🇮🇱", continent: "亚洲" },
    "PSE": { zh: "巴勒斯坦", en: "Palestine", flag: "🇵🇸", continent: "亚洲" },
    "SAU": { zh: "沙特阿拉伯", en: "Saudi Arabia", flag: "🇸🇦", continent: "亚洲" },
    "ARE": { zh: "阿联酋", en: "UAE", flag: "🇦🇪", continent: "亚洲" },
    "QAT": { zh: "卡塔尔", en: "Qatar", flag: "🇶🇦", continent: "亚洲" },
    "KWT": { zh: "科威特", en: "Kuwait", flag: "🇰🇼", continent: "亚洲" },
    "BHR": { zh: "巴林", en: "Bahrain", flag: "🇧🇭", continent: "亚洲" },
    "OMN": { zh: "阿曼", en: "Oman", flag: "🇴🇲", continent: "亚洲" },
    "YEM": { zh: "也门", en: "Yemen", flag: "🇾🇪", continent: "亚洲" },
    "TUR": { zh: "土耳其", en: "Turkey", flag: "🇹🇷", continent: "亚洲" },
    "CYP": { zh: "塞浦路斯", en: "Cyprus", flag: "🇨🇾", continent: "亚洲" },
    "GEO": { zh: "格鲁吉亚", en: "Georgia", flag: "🇬🇪", continent: "亚洲" },
    "ARM": { zh: "亚美尼亚", en: "Armenia", flag: "🇦🇲", continent: "亚洲" },
    "AZE": { zh: "阿塞拜疆", en: "Azerbaijan", flag: "🇦🇿", continent: "亚洲" },
    "KAZ": { zh: "哈萨克斯坦", en: "Kazakhstan", flag: "🇰🇿", continent: "亚洲" },
    "UZB": { zh: "乌兹别克斯坦", en: "Uzbekistan", flag: "🇺🇿", continent: "亚洲" },
    "KGZ": { zh: "吉尔吉斯斯坦", en: "Kyrgyzstan", flag: "🇰🇬", continent: "亚洲" },
    "TJK": { zh: "塔吉克斯坦", en: "Tajikistan", flag: "🇹🇯", continent: "亚洲" },
    "TKM": { zh: "土库曼斯坦", en: "Turkmenistan", flag: "🇹🇲", continent: "亚洲" },

    // ============ 欧洲 Europe ============
    "RUS": { zh: "俄罗斯", en: "Russia", flag: "🇷🇺", continent: "欧洲" },
    "GBR": { zh: "英国", en: "United Kingdom", flag: "🇬🇧", continent: "欧洲" },
    "FRA": { zh: "法国", en: "France", flag: "🇫🇷", continent: "欧洲" },
    "DEU": { zh: "德国", en: "Germany", flag: "🇩🇪", continent: "欧洲" },
    "ITA": { zh: "意大利", en: "Italy", flag: "🇮🇹", continent: "欧洲" },
    "ESP": { zh: "西班牙", en: "Spain", flag: "🇪🇸", continent: "欧洲" },
    "PRT": { zh: "葡萄牙", en: "Portugal", flag: "🇵🇹", continent: "欧洲" },
    "NLD": { zh: "荷兰", en: "Netherlands", flag: "🇳🇱", continent: "欧洲" },
    "BEL": { zh: "比利时", en: "Belgium", flag: "🇧🇪", continent: "欧洲" },
    "LUX": { zh: "卢森堡", en: "Luxembourg", flag: "🇱🇺", continent: "欧洲" },
    "CHE": { zh: "瑞士", en: "Switzerland", flag: "🇨🇭", continent: "欧洲" },
    "AUT": { zh: "奥地利", en: "Austria", flag: "🇦🇹", continent: "欧洲" },
    "POL": { zh: "波兰", en: "Poland", flag: "🇵🇱", continent: "欧洲" },
    "CZE": { zh: "捷克", en: "Czech Republic", flag: "🇨🇿", continent: "欧洲" },
    "SVK": { zh: "斯洛伐克", en: "Slovakia", flag: "🇸🇰", continent: "欧洲" },
    "HUN": { zh: "匈牙利", en: "Hungary", flag: "🇭🇺", continent: "欧洲" },
    "ROU": { zh: "罗马尼亚", en: "Romania", flag: "🇷🇴", continent: "欧洲" },
    "BGR": { zh: "保加利亚", en: "Bulgaria", flag: "🇧🇬", continent: "欧洲" },
    "GRC": { zh: "希腊", en: "Greece", flag: "🇬🇷", continent: "欧洲" },
    "ALB": { zh: "阿尔巴尼亚", en: "Albania", flag: "🇦🇱", continent: "欧洲" },
    "MKD": { zh: "北马其顿", en: "North Macedonia", flag: "🇲🇰", continent: "欧洲" },
    "SRB": { zh: "塞尔维亚", en: "Serbia", flag: "🇷🇸", continent: "欧洲" },
    "MNE": { zh: "黑山", en: "Montenegro", flag: "🇲🇪", continent: "欧洲" },
    "BIH": { zh: "波黑", en: "Bosnia and Herzegovina", flag: "🇧🇦", continent: "欧洲" },
    "HRV": { zh: "克罗地亚", en: "Croatia", flag: "🇭🇷", continent: "欧洲" },
    "SVN": { zh: "斯洛文尼亚", en: "Slovenia", flag: "🇸🇮", continent: "欧洲" },
    "KOS": { zh: "科索沃", en: "Kosovo", flag: "🇽🇰", continent: "欧洲" },
    "MDA": { zh: "摩尔多瓦", en: "Moldova", flag: "🇲🇩", continent: "欧洲" },
    "UKR": { zh: "乌克兰", en: "Ukraine", flag: "🇺🇦", continent: "欧洲" },
    "BLR": { zh: "白俄罗斯", en: "Belarus", flag: "🇧🇾", continent: "欧洲" },
    "LTU": { zh: "立陶宛", en: "Lithuania", flag: "🇱🇹", continent: "欧洲" },
    "LVA": { zh: "拉脱维亚", en: "Latvia", flag: "🇱🇻", continent: "欧洲" },
    "EST": { zh: "爱沙尼亚", en: "Estonia", flag: "🇪🇪", continent: "欧洲" },
    "FIN": { zh: "芬兰", en: "Finland", flag: "🇫🇮", continent: "欧洲" },
    "SWE": { zh: "瑞典", en: "Sweden", flag: "🇸🇪", continent: "欧洲" },
    "NOR": { zh: "挪威", en: "Norway", flag: "🇳🇴", continent: "欧洲" },
    "DNK": { zh: "丹麦", en: "Denmark", flag: "🇩🇰", continent: "欧洲" },
    "ISL": { zh: "冰岛", en: "Iceland", flag: "🇮🇸", continent: "欧洲" },
    "IRL": { zh: "爱尔兰", en: "Ireland", flag: "🇮🇪", continent: "欧洲" },
    "MLT": { zh: "马耳他", en: "Malta", flag: "🇲🇹", continent: "欧洲" },
    "AND": { zh: "安道尔", en: "Andorra", flag: "🇦🇩", continent: "欧洲" },
    "MCO": { zh: "摩纳哥", en: "Monaco", flag: "🇲🇨", continent: "欧洲" },
    "LIE": { zh: "列支敦士登", en: "Liechtenstein", flag: "🇱🇮", continent: "欧洲" },
    "SMR": { zh: "圣马力诺", en: "San Marino", flag: "🇸🇲", continent: "欧洲" },
    "VAT": { zh: "梵蒂冈", en: "Vatican City", flag: "🇻🇦", continent: "欧洲" },

    // ============ 北美洲 North America ============
    "USA": { zh: "美国", en: "United States", flag: "🇺🇸", continent: "北美洲" },
    "CAN": { zh: "加拿大", en: "Canada", flag: "🇨🇦", continent: "北美洲" },
    "MEX": { zh: "墨西哥", en: "Mexico", flag: "🇲🇽", continent: "北美洲" },
    "GTM": { zh: "危地马拉", en: "Guatemala", flag: "🇬🇹", continent: "北美洲" },
    "BLZ": { zh: "伯利兹", en: "Belize", flag: "🇧🇿", continent: "北美洲" },
    "HND": { zh: "洪都拉斯", en: "Honduras", flag: "🇭🇳", continent: "北美洲" },
    "SLV": { zh: "萨尔瓦多", en: "El Salvador", flag: "🇸🇻", continent: "北美洲" },
    "NIC": { zh: "尼加拉瓜", en: "Nicaragua", flag: "🇳🇮", continent: "北美洲" },
    "CRI": { zh: "哥斯达黎加", en: "Costa Rica", flag: "🇨🇷", continent: "北美洲" },
    "PAN": { zh: "巴拿马", en: "Panama", flag: "🇵🇦", continent: "北美洲" },
    "CUB": { zh: "古巴", en: "Cuba", flag: "🇨🇺", continent: "北美洲" },
    "JAM": { zh: "牙买加", en: "Jamaica", flag: "🇯🇲", continent: "北美洲" },
    "HTI": { zh: "海地", en: "Haiti", flag: "🇭🇹", continent: "北美洲" },
    "DOM": { zh: "多米尼加", en: "Dominican Republic", flag: "🇩🇴", continent: "北美洲" },
    "BHS": { zh: "巴哈马", en: "Bahamas", flag: "🇧🇸", continent: "北美洲" },
    "TTO": { zh: "特立尼达和多巴哥", en: "Trinidad and Tobago", flag: "🇹🇹", continent: "北美洲" },

    // ============ 南美洲 South America ============
    "BRA": { zh: "巴西", en: "Brazil", flag: "🇧🇷", continent: "南美洲" },
    "ARG": { zh: "阿根廷", en: "Argentina", flag: "🇦🇷", continent: "南美洲" },
    "CHL": { zh: "智利", en: "Chile", flag: "🇨🇱", continent: "南美洲" },
    "PER": { zh: "秘鲁", en: "Peru", flag: "🇵🇪", continent: "南美洲" },
    "COL": { zh: "哥伦比亚", en: "Colombia", flag: "🇨🇴", continent: "南美洲" },
    "VEN": { zh: "委内瑞拉", en: "Venezuela", flag: "🇻🇪", continent: "南美洲" },
    "ECU": { zh: "厄瓜多尔", en: "Ecuador", flag: "🇪🇨", continent: "南美洲" },
    "BOL": { zh: "玻利维亚", en: "Bolivia", flag: "🇧🇴", continent: "南美洲" },
    "PRY": { zh: "巴拉圭", en: "Paraguay", flag: "🇵🇾", continent: "南美洲" },
    "URY": { zh: "乌拉圭", en: "Uruguay", flag: "🇺🇾", continent: "南美洲" },
    "GUY": { zh: "圭亚那", en: "Guyana", flag: "🇬🇾", continent: "南美洲" },
    "SUR": { zh: "苏里南", en: "Suriname", flag: "🇸🇷", continent: "南美洲" },
    "GUF": { zh: "法属圭亚那", en: "French Guiana", flag: "🇬🇫", continent: "南美洲" },

    // ============ 非洲 Africa ============
    "EGY": { zh: "埃及", en: "Egypt", flag: "🇪🇬", continent: "非洲" },
    "LBY": { zh: "利比亚", en: "Libya", flag: "🇱🇾", continent: "非洲" },
    "TUN": { zh: "突尼斯", en: "Tunisia", flag: "🇹🇳", continent: "非洲" },
    "DZA": { zh: "阿尔及利亚", en: "Algeria", flag: "🇩🇿", continent: "非洲" },
    "MAR": { zh: "摩洛哥", en: "Morocco", flag: "🇲🇦", continent: "非洲" },
    "ESH": { zh: "西撒哈拉", en: "Western Sahara", flag: "🇪🇭", continent: "非洲" },
    "SDN": { zh: "苏丹", en: "Sudan", flag: "🇸🇩", continent: "非洲" },
    "SSD": { zh: "南苏丹", en: "South Sudan", flag: "🇸🇸", continent: "非洲" },
    "ETH": { zh: "埃塞俄比亚", en: "Ethiopia", flag: "🇪🇹", continent: "非洲" },
    "ERI": { zh: "厄立特里亚", en: "Eritrea", flag: "🇪🇷", continent: "非洲" },
    "DJI": { zh: "吉布提", en: "Djibouti", flag: "🇩🇯", continent: "非洲" },
    "SOM": { zh: "索马里", en: "Somalia", flag: "🇸🇴", continent: "非洲" },
    "KEN": { zh: "肯尼亚", en: "Kenya", flag: "🇰🇪", continent: "非洲" },
    "UGA": { zh: "乌干达", en: "Uganda", flag: "🇺🇬", continent: "非洲" },
    "RWA": { zh: "卢旺达", en: "Rwanda", flag: "🇷🇼", continent: "非洲" },
    "BDI": { zh: "布隆迪", en: "Burundi", flag: "🇧🇮", continent: "非洲" },
    "TZA": { zh: "坦桑尼亚", en: "Tanzania", flag: "🇹🇿", continent: "非洲" },
    "MWI": { zh: "马拉维", en: "Malawi", flag: "🇲🇼", continent: "非洲" },
    "MOZ": { zh: "莫桑比克", en: "Mozambique", flag: "🇲🇿", continent: "非洲" },
    "ZMB": { zh: "赞比亚", en: "Zambia", flag: "🇿🇲", continent: "非洲" },
    "ZWE": { zh: "津巴布韦", en: "Zimbabwe", flag: "🇿🇼", continent: "非洲" },
    "BWA": { zh: "博茨瓦纳", en: "Botswana", flag: "🇧🇼", continent: "非洲" },
    "NAM": { zh: "纳米比亚", en: "Namibia", flag: "🇳🇦", continent: "非洲" },
    "ZAF": { zh: "南非", en: "South Africa", flag: "🇿🇦", continent: "非洲" },
    "LSO": { zh: "莱索托", en: "Lesotho", flag: "🇱🇸", continent: "非洲" },
    "SWZ": { zh: "斯威士兰", en: "Eswatini", flag: "🇸🇿", continent: "非洲" },
    "MDG": { zh: "马达加斯加", en: "Madagascar", flag: "🇲🇬", continent: "非洲" },
    "MUS": { zh: "毛里求斯", en: "Mauritius", flag: "🇲🇺", continent: "非洲" },
    "SYC": { zh: "塞舌尔", en: "Seychelles", flag: "🇸🇨", continent: "非洲" },
    "AGO": { zh: "安哥拉", en: "Angola", flag: "🇦🇴", continent: "非洲" },
    "COD": { zh: "刚果(金)", en: "DR Congo", flag: "🇨🇩", continent: "非洲" },
    "COG": { zh: "刚果(布)", en: "Congo", flag: "🇨🇬", continent: "非洲" },
    "GAB": { zh: "加蓬", en: "Gabon", flag: "🇬🇦", continent: "非洲" },
    "GNQ": { zh: "赤道几内亚", en: "Equatorial Guinea", flag: "🇬🇶", continent: "非洲" },
    "CMR": { zh: "喀麦隆", en: "Cameroon", flag: "🇨🇲", continent: "非洲" },
    "CAF": { zh: "中非共和国", en: "Central African Republic", flag: "🇨🇫", continent: "非洲" },
    "TCD": { zh: "乍得", en: "Chad", flag: "🇹🇩", continent: "非洲" },
    "NER": { zh: "尼日尔", en: "Niger", flag: "🇳🇪", continent: "非洲" },
    "NGA": { zh: "尼日利亚", en: "Nigeria", flag: "🇳🇬", continent: "非洲" },
    "BEN": { zh: "贝宁", en: "Benin", flag: "🇧🇯", continent: "非洲" },
    "TGO": { zh: "多哥", en: "Togo", flag: "🇹🇬", continent: "非洲" },
    "GHA": { zh: "加纳", en: "Ghana", flag: "🇬🇭", continent: "非洲" },
    "CIV": { zh: "科特迪瓦", en: "Côte d'Ivoire", flag: "🇨🇮", continent: "非洲" },
    "LBR": { zh: "利比里亚", en: "Liberia", flag: "🇱🇷", continent: "非洲" },
    "SLE": { zh: "塞拉利昂", en: "Sierra Leone", flag: "🇸🇱", continent: "非洲" },
    "GIN": { zh: "几内亚", en: "Guinea", flag: "🇬🇳", continent: "非洲" },
    "GNB": { zh: "几内亚比绍", en: "Guinea-Bissau", flag: "🇬🇼", continent: "非洲" },
    "SEN": { zh: "塞内加尔", en: "Senegal", flag: "🇸🇳", continent: "非洲" },
    "GMB": { zh: "冈比亚", en: "Gambia", flag: "🇬🇲", continent: "非洲" },
    "MLI": { zh: "马里", en: "Mali", flag: "🇲🇱", continent: "非洲" },
    "BFA": { zh: "布基纳法索", en: "Burkina Faso", flag: "🇧🇫", continent: "非洲" },
    "MRT": { zh: "毛里塔尼亚", en: "Mauritania", flag: "🇲🇷", continent: "非洲" },
    "CPV": { zh: "佛得角", en: "Cape Verde", flag: "🇨🇻", continent: "非洲" },
    "STP": { zh: "圣多美和普林西比", en: "São Tomé and Príncipe", flag: "🇸🇹", continent: "非洲" },
    "COM": { zh: "科摩罗", en: "Comoros", flag: "🇰🇲", continent: "非洲" },

    // ============ 大洋洲 Oceania ============
    "AUS": { zh: "澳大利亚", en: "Australia", flag: "🇦🇺", continent: "大洋洲" },
    "NZL": { zh: "新西兰", en: "New Zealand", flag: "🇳🇿", continent: "大洋洲" },
    "PNG": { zh: "巴布亚新几内亚", en: "Papua New Guinea", flag: "🇵🇬", continent: "大洋洲" },
    "FJI": { zh: "斐济", en: "Fiji", flag: "🇫🇯", continent: "大洋洲" },
    "SLB": { zh: "所罗门群岛", en: "Solomon Islands", flag: "🇸🇧", continent: "大洋洲" },
    "VUT": { zh: "瓦努阿图", en: "Vanuatu", flag: "🇻🇺", continent: "大洋洲" },
    "NCL": { zh: "新喀里多尼亚", en: "New Caledonia", flag: "🇳🇨", continent: "大洋洲" },
    "PYF": { zh: "法属波利尼西亚", en: "French Polynesia", flag: "🇵🇫", continent: "大洋洲" },
    "WSM": { zh: "萨摩亚", en: "Samoa", flag: "🇼🇸", continent: "大洋洲" },
    "TON": { zh: "汤加", en: "Tonga", flag: "🇹🇴", continent: "大洋洲" },
    "KIR": { zh: "基里巴斯", en: "Kiribati", flag: "🇰🇮", continent: "大洋洲" },
    "MHL": { zh: "马绍尔群岛", en: "Marshall Islands", flag: "🇲🇭", continent: "大洋洲" },
    "FSM": { zh: "密克罗尼西亚", en: "Micronesia", flag: "🇫🇲", continent: "大洋洲" },
    "PLW": { zh: "帕劳", en: "Palau", flag: "🇵🇼", continent: "大洋洲" },
    "NRU": { zh: "瑙鲁", en: "Nauru", flag: "🇳🇷", continent: "大洋洲" },
    "TUV": { zh: "图瓦卢", en: "Tuvalu", flag: "🇹🇻", continent: "大洋洲" },

    // ============ 南极 ============
    "ATA": { zh: "南极洲", en: "Antarctica", flag: "🇦🇶", continent: "南极洲" },

    // ============ 一些特殊地区 ============
    "GRL": { zh: "格陵兰", en: "Greenland", flag: "🇬🇱", continent: "北美洲" },
    "FLK": { zh: "福克兰群岛", en: "Falkland Islands", flag: "🇫🇰", continent: "南美洲" },
    "PRI": { zh: "波多黎各", en: "Puerto Rico", flag: "🇵🇷", continent: "北美洲" }
};

/**
 * 备用名称查询表 - 用于处理 GeoJSON 中 ISO 代码缺失或不一致的情况
 * key 为可能出现的国家名（小写）
 */
const COUNTRY_NAME_MAP = {
    "china": "CHN",
    "people's republic of china": "CHN",
    "united states of america": "USA",
    "united states": "USA",
    "russian federation": "RUS",
    "russia": "RUS",
    "south korea": "KOR",
    "republic of korea": "KOR",
    "north korea": "PRK",
    "democratic people's republic of korea": "PRK",
    "iran": "IRN",
    "syria": "SYR",
    "vietnam": "VNM",
    "laos": "LAO",
    "myanmar": "MMR",
    "burma": "MMR",
    "uk": "GBR",
    "united kingdom": "GBR",
    "great britain": "GBR",
    "czech republic": "CZE",
    "czechia": "CZE",
    "macedonia": "MKD",
    "north macedonia": "MKD",
    "bosnia and herzegovina": "BIH",
    "moldova": "MDA",
    "tanzania": "TZA",
    "democratic republic of the congo": "COD",
    "dr congo": "COD",
    "republic of the congo": "COG",
    "congo": "COG",
    "ivory coast": "CIV",
    "côte d'ivoire": "CIV",
    "cape verde": "CPV",
    "cabo verde": "CPV",
    "swaziland": "SWZ",
    "eswatini": "SWZ",
    "east timor": "TLS",
    "timor-leste": "TLS",
    "taiwan": "TWN",
    "palestine": "PSE",
    "kosovo": "KOS",
    "antarctica": "ATA"
};

/**
 * 查询国家信息
 * @param {string} isoCode ISO_A3 代码
 * @param {string} countryName 国家名（备用）
 */
function getCountryInfo(isoCode, countryName) {
    if (isoCode && COUNTRIES_DATA[isoCode]) {
        return { code: isoCode, ...COUNTRIES_DATA[isoCode] };
    }
    if (countryName) {
        const lookupKey = countryName.toLowerCase().trim();
        const code = COUNTRY_NAME_MAP[lookupKey];
        if (code && COUNTRIES_DATA[code]) {
            return { code, ...COUNTRIES_DATA[code] };
        }
    }
    return {
        code: isoCode || countryName || "UNK",
        zh: countryName || "未知地区",
        en: countryName || "Unknown",
        flag: "🏳️",
        continent: "其他"
    };
}
